language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
  - 4
  - 5
sudo: false
notifications:
  email: false
  pushover:
    api_key:
      secure: "fMmMU3Da3kRwtABvhgWM2vOMvXh8QuFfbu1eYMRH6lt0zlY9CLjXQLSTbZxzsjVb7CQi9zF7fgUAokJl3pRWLafBs/SfLE0dRZouP6ZbjD74HzkP8PBShN4DxYiSDHjaS9J6AvHlDtKKXXQ3GyoMgkHFfxYSkq45YL8IJlMzxCn/EccRVjXs1mD7vcBvU0k3MNQ/rQV9qeDZ+VBktdxZSJHKieomKoO4DwRO5BVc/ro9cL2z5x0JMLkpBV8dFsCQy/9VxoLuXNXOTlQ3USX0DHFfHImnCOfAjBYa4/i2OHOLJSG8AdC5AgGujQTyOfBBV7WY2iplX2Rjj8lWFUvGF0+MbXMamjg7ULLlC2MW4sQ93K+hDiKCP9YDRnlfsoCtpwREbzjfs3+iIEJ63Cz3GNHPqpipi18gO5OB0eSe+OyvlPjQSSb87hhncDBppYmFFC3w29qRIl5qO/LKWdFH9Nbga/TSuqd2mc84xAdSAGAyDRXWCxGZZ1joPJE3XgvrmYsZpUN0jcJg0Vyw50g6V7SF3fK6/jEKN+waVTNiIgvSEOd2n3SL+Jc+t+UupmjHA6f5suWhgFnIArccRgpi2AvGLI5mf5hH6rCYSdOxynmOVB3rAhZsyfwNbOhTog/tKeImOs6M7bSV+qa7TIZPzNDfbWeCvxeO2QWFHLrBC2c="
    users:
      -
        secure: "OaMHse6qFcmivQDfRGjFAWTSMklvK+eRw5/ScjMS2TfIe+taCw4itXI83X8CzOe/YYTeiGNFDLUxAeCwuFQQtuRBEttdv57Ru24wmFTBqmXI4mq5rS0Cz70H6zgcO6tiI4xpzl10EC+7cuzk5GRQVg7AqwC48kLOX3SAP77aoFtcDYh50TJNcdzxVPnN2CWpIv5VG9zLIHaldkL3vo+c660eWcb11OVjrcnP19nkI2uY2TSMBAkDYn/MLgE6O5LL/fVYXThM97dVp2Q3dmZe0iSCwgKS5y4nkd/A4LguAhmdNoTaUorivGNo4rrzDFPgeK9oGT4QpXmQm83V65Zo99c5YUC44GhMoiqzfNokLQ6KlkwnT0pyYqSO1gfZVufTrlWSHLf5JX5iAMXzcFIitbA3trDu1WVf1SStXJLs2idYEr7N0iwLigUUjq2aOXwoSs7BpMmIQ5yLQJbUdaEWkbAJFqNp9Sdh2raO7oOBIYjowoQ9oNOe1KkUqr6Cwxz1r+q2vmtRydzUNSMUQzOKXuFHFcV+HtRsCBI2aXzEtwW26oFsQO2ryHkgceCvfcc3cZaQXzZL0yjhk/7Z9AYDUT789jLrEIs/uMKLItcbhvILlWMT8n0WZOTuuVzTeAn0+jzrwmXc+bNkL/qf5b+jkM3Hv9bTQAuj3X4D2yvpEBY="
